version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building the Next.js app..."
      - npm run build

  post_build:
  commands:
    - echo "Fetching bucket name from CloudFormation outputs..."
    - |
      BUCKET_NAME=$(aws cloudformation describe-stacks \
        --stack-name signin-frontend-stack \
        --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
        --output text)
      echo "Uploading static files to S3 bucket: $BUCKET_NAME"
      aws s3 sync out/ s3://$BUCKET_NAME/ --delete


artifacts:
  files:
    - '**/*'
  base-directory: out
